import { DataSource } from 'typeorm';
import { PermissionGroup } from '../../modules/permission-groups/entities/permission-group.entity';
import { Permission } from '../../modules/permissions/entities/permission.entity';

export default class PermissionSeeder {
  public async run(_: any, connection: DataSource): Promise<any> {
    const entities = [PermissionGroup, Permission];

    for (const entity of entities) {
      const repository = connection.getRepository(entity);
      await repository.query('SET FOREIGN_KEY_CHECKS = 0;');
      await repository.query(`TRUNCATE TABLE ${repository.metadata.tableName};`);
      await repository.query('SET FOREIGN_KEY_CHECKS = 1;');
    }

    const permissionGroupRepository = connection.getRepository(PermissionGroup);
    const permissionRepository = connection.getRepository(Permission);

    const permissionGroups = await permissionGroupRepository.save([
      {
        id: 'cbf4b3b0-0b1b-4b3b-8b3b-0b1b4b3b8b3b',
        name: 'User',
        description: 'User management',
        slug: 'user',
      },
      {
        id: 'cbf4b3b0-0b1b-4b3b-8b3b-0b1b4b3b8b3c',
        name: 'Vendor',
        description: 'Vendor management',
        slug: 'vendor',
      },
      {
        id: 'cbf4b3b0-0b1b-4b3b-8b3b-0b1b4b3b8b3d',
        name: 'Role',
        description: 'Role management',
        slug: 'role',
      },
      {
        id: 'cbf4b3b0-0b1b-4b3b-8b3b-0b1b4b3b8b3f',
        name: 'Issue',
        description: 'Issue management',
        slug: 'slug',
      },
      {
        id: 'cbf4b3b0-0b1b-4b3b-8b3b-0b1b4b3b8b3e',
        name: 'Patient',
        description: 'Patient management',
        slug: 'patient',
      },
      {
        id: 'cbf4b3b0-0b1b-4b3b-8b3b-0b1b4b3b8b3a',
        name: 'Appointment management',
        description: 'Appointment management',
        slug: 'appointment',
      },
      {
        id: 'cbf4b3b0-0b1b-4b3b-8b3b-0b1b4b3b8b3h',
        name: 'Dashboard',
        description: 'Dashboard management',
        slug: 'dashboard',
      },
      {
        id: 'cbf4b3b0-0b1b-4b3b-8b3b-0b1b4b3b8b3i',
        name: 'Site',
        description: 'Site management',
        slug: 'site',
      },
      {
        id: 'cbf4b3b0-0b1b-4b3b-8b3b-0b1b4b3b8b3j',
        name: 'Trial',
        description: 'Trial management',
        slug: 'trial',
      },
      {
        id: 'cbf4b3b0-0b1b-4b3b-8b3b-0b1b4b3b8b3k',
        name: 'Risk',
        description: 'Risk management',
        slug: 'risk',
      },
      {
        id: 'cbf4b3b0-0b1b-4b3b-8b3b-0b1b4b3b8b3l',
        name: 'Regulatory Compliance',
        description: 'Regulatory Compliance management',
        slug: 'regulatory-compliance',
      },
      {
        id: 'cbf4b3b0-0b1b-4b3b-8b3b-0b1b4b3b8b3m',
        name: 'Transactions',
        description: 'Transactions management',
        slug: 'transactions',
      },
      {
        id: 'cbf4b3b0-0b1b-4b3b-8b3b-0b1b4b3b8b3n',
        name: 'Reports',
        description: 'Reports management',
        slug: 'reports',
      },
      {
        id: 'cbf4b3b0-0b1b-4b3b-8b3b-0b1b4b3b8b3o',
        name: 'Settings',
        description: 'Settings management',
        slug: 'settings',
      },
      {
        id: 'cbf4b3b0-0b1b-4b3b-8b3b-0b1b4b3b9b3b',
        name: 'Fraud',
        description: 'Fraud management',
        slug: 'fraud',
      },
      {
        id: 'cbf4b3b0-0b1b-4b3b-8b3b-0b1ba3b8b3b',
        name: 'Supply Overview',
        description: 'Supply Overview management',
        slug: 'supply-overview',
      },
      {
        id: 'cbf4b3b0-0b1b-4b3b-8b3b-0b1ba3b8b3c',
        name: 'Finance Overview',
        description: 'Finance Overview management',
        slug: 'finance-overview',
      },
      {
        id: 'cbf4b3b0-0b1b-4b3b-8b3b-0b1ba3b8b3d',
        name: 'Budget Overview',
        description: 'Budget Overview management',
        slug: 'budget-overview',
      },
      {
        id: 'cbf4b3b0-0b1b-4b3b-8b3b-0b1ba3b8b3e',
        name: 'Deliveries',
        description: 'Deliveries management',
        slug: 'deliveries',
      },
      {
        id: 'cbf4b3b0-0b1b-4b3b-8b3b-0b1ba3b8b4b',
        name: 'Sponsor',
        description: 'Sponsor management',
        slug: 'sponsor',
      },
    ]);

    const permissions = await permissionRepository.save([
      {
        id: 'cbf4b3b0-0b1b-4b3b-8b3b-0b1b4b3b8b3g',
        name: 'Create user',
        description: 'Create user',
        slug: 'create-user',
        permissionGroupId: permissionGroups[0].id,
      },
      {
        id: 'cbf4b3b0-0b1b-4b3b-8b3b-0b1b4b3b8b3h',
        name: 'Update user',
        description: 'Update user',
        slug: 'update-user',
        permissionGroupId: permissionGroups[0].id,
      },
      {
        id: 'cbf4b3b0-0b1b-4b3b-8b3b-0b1b4b3b8b3i',
        name: 'Delete user',
        description: 'Delete user',
        slug: 'delete-user',
        permissionGroupId: permissionGroups[0].id,
      },
      {
        id: 'af7c1fe6-d669-414e-b066-e9733f0de7a8',
        name: 'View user',
        description: 'View user',
        slug: 'view-user',
        permissionGroupId: permissionGroups[0].id,
      },
      {
        id: 'cbf4b3b0-0b1b-4b3b-8b3b-0b1b4b3b8b3j',
        name: 'Create vendor',
        description: 'Create vendor',
        slug: 'create-vendor',
        permissionGroupId: permissionGroups[1].id,
      },
      {
        id: 'cbf4b3b0-0b1b-4b3b-8b3b-0b1b4b3b8b3k',
        name: 'View vendor',
        description: 'View vendor',
        slug: 'view-vendor',
        permissionGroupId: permissionGroups[1].id,
      },
      {
        id: 'cbf4b3b0-0b1b-4b3b-8b3b-0b1b4b3b8b3m',
        name: 'Create role',
        description: 'Create role',
        slug: 'create-role',
        permissionGroupId: permissionGroups[2].id,
      },
      {
        id: 'cbf4b3b0-0b1b-4b3b-8b3b-0b1b4b3b8b3n',
        name: 'Update role',
        description: 'Update role',
        slug: 'update-role',
        permissionGroupId: permissionGroups[2].id,
      },
      {
        id: 'cbf4b3b0-0b1b-4b3b-8b3b-0b1b4b3b8b3q',
        name: 'Create issue',
        description: 'Create issue',
        slug: 'create-issue',
        permissionGroupId: permissionGroups[7].id,
      },
      {
        id: 'cbf4b3b0-0b1b-4b3b-8b3b-0b1b4b3b8b3r',
        name: 'Update issue',
        description: 'Update issue',
        slug: 'update-issue',
        permissionGroupId: permissionGroups[7].id,
      },
      {
        id: 'cbf4b3b0-0b1b-4b3b-8b3b-0b1b4b3b8b3s',
        name: 'Delete issue',
        description: 'Delete issue',
        slug: 'delete-issue',
        permissionGroupId: permissionGroups[7].id,
      },
      {
        id: 'cbf4b3b0-0b1b-4b3b-8b3b-0b1b4b3b8b3t',
        name: 'Create patient',
        description: 'Create patient',
        slug: 'create-patient',
        permissionGroupId: permissionGroups[4].id,
      },
      {
        id: 'cbf4b3b0-0b1b-4b3b-8b3b-0b1b4b3b8b3u',
        name: 'Update patient',
        description: 'Update patient',
        slug: 'update-patient',
        permissionGroupId: permissionGroups[4].id,
      },
      {
        id: 'cbf4b3b0-0b1b-4b3b-8b3b-0b1b4b3b8b3v',
        name: 'Delete patient',
        description: 'Delete patient',
        slug: 'delete-patient',
        permissionGroupId: permissionGroups[4].id,
      },
      {
        id: 'cbf4b3b0-0b1b-4b3b-8b3b-0b1b4b3b8b3a',
        name: 'View patient',
        description: 'View patient',
        slug: 'view-patient',
        permissionGroupId: permissionGroups[4].id,
      },
      {
        id: 'cbf4b3b0-0b1b-4b3b-8b3b-0b1b4b3b8b3w',
        name: 'Create appointment',
        description: 'Create appointment',
        slug: 'create-appointment',
        permissionGroupId: permissionGroups[5].id,
      },
      {
        id: 'cbf4b3b0-0b1b-4b3b-8b3b-0b1b4b3b8b3x',
        name: 'Update appointment',
        description: 'Update appointment',
        slug: 'update-appointment',
        permissionGroupId: permissionGroups[5].id,
      },
      {
        id: 'cbf4b3b0-0b1b-4b3b-8b3b-0b1b4b3b8b3y',
        name: 'Delete appointment',
        description: 'Delete appointment',
        slug: 'delete-appointment',
        permissionGroupId: permissionGroups[5].id,
      },
      {
        id: 'cbf4b3b0-0b1b-4b3b-8b3b-0b1b4b3b8baa',
        name: 'View appointment',
        description: 'View appointment',
        slug: 'view-appointment',
        permissionGroupId: permissionGroups[5].id,
      },
      {
        id: 'cbf4b3b0-0b1b-4b3b-8b3b-0b1b4b3b8bab',
        name: 'View dashboard',
        description: 'View dashboard',
        slug: 'view-dashboard',
        permissionGroupId: permissionGroups[6].id,
      },
      {
        id: 'cbf4b3b0-0b1b-4b3b-8b3b-0b1b4b3b8bag',
        name: 'View alerts and notifications',
        description: 'View alerts and notifications',
        slug: 'view-alerts-and-notifications',
        permissionGroupId: permissionGroups[13].id,
      },
      {
        id: 'cbf4b3b0-0b1b-4b3b-8b3b-0b1b4b3b8bah',
        name: 'View sites',
        description: 'View sites',
        slug: 'view-sites',
        permissionGroupId: permissionGroups[7].id,
      },
      {
        id: 'cbf4b3b0-0b1b-4b3b-8b3b-0b1ba3b8b4z',
        name: 'Create site',
        description: 'Create site',
        slug: 'create-site',
        permissionGroupId: permissionGroups[7].id,
      },
      {
        id: 'cbf4b3b0-0b1b-4b3b-8b3b-0b1ba3b8baa',
        name: 'Update site',
        description: 'Update site',
        slug: 'update-site',
        permissionGroupId: permissionGroups[7].id,
      },
      {
        id: 'ab3b7f72-7541-49d3-ae02-aa70a28e14f0',
        name: 'Create trial',
        slug: 'create-trial',
        description: 'Create trial',
        permissionGroupId: permissionGroups[8].id,
      },
      {
        id: 'e03f0f34-ce6b-4c38-bc39-5924816acb26',
        name: 'Update trial',
        slug: 'update-trial',
        description: 'Update trial',
        permissionGroupId: permissionGroups[8].id,
      },
      {
        id: 'cbf4b3b0-0b1b-4b3b-8b3b-0b1ba3b8b3k',
        name: 'Delete trial',
        slug: 'delete-trial',
        description: 'Delete trial',
        permissionGroupId: permissionGroups[8].id,
      },
      {
        id: 'cbf4b3b0-0b1b-4b3b-8b3b-0b1ba3b8b3l',
        name: 'View trial',
        slug: 'view-trial',
        description: 'View trial',
        permissionGroupId: permissionGroups[8].id,
      },
      {
        id: 'cbf4b3b0-0b1b-4b3b-8b3b-0b1ba3b8b3m',
        name: 'Assign trial',
        slug: 'assign-trial',
        description: 'Assign trial',
        permissionGroupId: permissionGroups[8].id,
      },
      {
        id: 'cbf4b3b0-0b1b-4b3b-8b3b-0b1ba3b8b3n',
        name: 'Update risk',
        slug: 'update-risk',
        description: 'Update risk',
        permissionGroupId: permissionGroups[9].id,
      },
      {
        id: 'cbf4b3b0-0b1b-4b3b-8b3b-0b1ba3b8b3o',
        name: 'View risk',
        slug: 'view-risk',
        description: 'View risk',
        permissionGroupId: permissionGroups[9].id,
      },
      {
        id: 'cbf4b3b0-0b1b-4b3b-8b3b-0b1ba3b8b3p',
        name: 'manage risk',
        slug: 'manage-risk',
        description: 'manage risk',
        permissionGroupId: permissionGroups[9].id,
      },
      {
        id: 'cbf4b3b0-0b1b-4b3b-8b3b-0b1ba3b8b3q',
        name: 'view fraud',
        slug: 'view-fraud',
        description: 'view fraud',
        permissionGroupId: permissionGroups[16].id,
      },
      {
        id: 'cbf4b3b0-0b1b-4b3b-8b3b-0b1b4b3b8bar',
        name: 'report fraud',
        slug: 'report-fraud',
        description: 'report fraud',
        permissionGroupId: permissionGroups[16].id,
      },
      {
        id: 'cbf4b3b0-0b1b-4b3b-8b3b-0b1b4b3b8bas',
        name: 'dismiss fraud',
        slug: 'dismiss-fraud',
        description: 'dismiss fraud',
        permissionGroupId: permissionGroups[16].id,
      },
      {
        id: 'cbf4b3b0-0b1b-4b3b-8b3b-0b1ba3b8b3r',
        name: 'Create transactions',
        slug: 'create-transactions',
        description: 'Create transactions',
        permissionGroupId: permissionGroups[11].id,
      },
      {
        id: 'cbf4b3b0-0b1b-4b3b-8b3b-0b1ba3b8b3s',
        name: 'Update transactions',
        slug: 'update-transactions',
        description: 'Update transactions',
        permissionGroupId: permissionGroups[11].id,
      },
      {
        id: 'cbf4b3b0-0b1b-4b3b-8b3b-0b1ba3b8b3t',
        name: 'Delete transactions',
        slug: 'delete-transactions',
        description: 'Delete transactions',
        permissionGroupId: permissionGroups[11].id,
      },
      {
        id: 'cbf4b3b0-0b1b-4b3b-8b3b-0b1ba3b8b3u',
        name: 'View transactions',
        slug: 'view-transactions',
        description: 'View transactions',
        permissionGroupId: permissionGroups[11].id,
      },
      {
        id: 'cbf4b3b0-0b1b-4b3b-8b3b-0b1b4b3b8bal',
        name: 'View reports',
        description: 'View reports',
        slug: 'view-reports',
        permissionGroupId: permissionGroups[12].id,
      },
      {
        id: 'cbf4b3b0-0b1b-4b3b-8b3b-0b1b4b3b8bam',
        name: 'Create regulation',
        slug: 'create-regulation',
        description: 'Create regulation',
        permissionGroupId: permissionGroups[10].id,
      },
      {
        id: 'cbf4b3b0-0b1b-4b3b-8b3b-0b1b4b3b8ban',
        name: 'Update regulation',
        slug: 'update-regulation',
        description: 'Update regulation',
        permissionGroupId: permissionGroups[10].id,
      },
      {
        id: 'cbf4b3b0-0b1b-4b3b-8b3b-0b1b4b3b8bap',
        name: 'Delete regulation',
        slug: 'delete-regulation',
        description: 'Delete regulation',
        permissionGroupId: permissionGroups[10].id,
      },
      {
        id: 'cbf4b3b0-0b1b-4b3b-8b3b-0b1b4b3b8baq',
        name: 'View regulation',
        slug: 'view-regulation',
        description: 'View regulation',
        permissionGroupId: permissionGroups[10].id,
      },
      {
        id: 'cbf4b3b0-0b1b-4b3b-8b3b-0b1b4b3ba3ba',
        name: 'Create supply',
        slug: 'create-supply',
        description: 'Create supply',
        permissionGroupId: permissionGroups[15].id,
      },
      {
        id: 'cbf4b3b0-0b1b-4b3b-8b3b-0b1b4b3ba3bb',
        name: 'Update supply',
        slug: 'update-supply',
        description: 'Update supply',
        permissionGroupId: permissionGroups[15].id,
      },
      {
        id: 'cbf4b3b0-0b1b-4b3b-8b3b-0b1b4b3ba3bc',
        name: 'Delete supply',
        slug: 'delete-supply',
        description: 'Delete supply',
        permissionGroupId: permissionGroups[15].id,
      },
      {
        id: 'cbf4b3b0-0b1b-4b3b-8b3b-0b1b4b3ba3bd',
        name: 'View supply',
        slug: 'view-supply',
        description: 'View supply',
        permissionGroupId: permissionGroups[15].id,
      },
      {
        id: 'cbf4b3b0-0b1b-4b3b-8b3b-0b1ba3b8b3v',
        name: 'Create finance',
        slug: 'create-finance',
        description: 'Create finance',
        permissionGroupId: permissionGroups[16].id,
      },
      {
        id: 'cbf4b3b0-0b1b-4b3b-8b3b-0b1ba3b8b3w',
        name: 'Update finance',
        slug: 'update-finance',
        description: 'Update finance',
        permissionGroupId: permissionGroups[16].id,
      },
      {
        id: 'cbf4b3b0-0b1b-4b3b-8b3b-0b1ba3b8b3x',
        name: 'Delete finance',
        slug: 'delete-finance',
        description: 'Delete finance',
        permissionGroupId: permissionGroups[16].id,
      },
      {
        id: 'cbf4b3b0-0b1b-4b3b-8b3b-0b1ba3b8b3y',
        name: 'View finance',
        slug: 'view-finance',
        description: 'View finance',
        permissionGroupId: permissionGroups[16].id,
      },
      {
        id: 'cbf4b3b0-0b1b-4b3b-8b3b-0b1ba3b8b3z',
        name: 'Create budget',
        slug: 'create-budget',
        description: 'Create budget',
        permissionGroupId: permissionGroups[16].id,
      },
      {
        id: 'cbf4b3b0-0b1b-4b3b-8b3b-0b1ba3b8b3aa',
        name: 'Update budget',
        slug: 'update-budget',
        description: 'Update budget',
        permissionGroupId: permissionGroups[16].id,
      },
      {
        id: 'cbf4b3b0-0b1b-4b3b-8b3b-0b1ba3b8b3ab',
        name: 'Delete budget',
        slug: 'delete-budget',
        description: 'Delete budget',
        permissionGroupId: permissionGroups[16].id,
      },
      {
        id: 'cbf4b3b0-0b1b-4b3b-8b3b-0b1ba3b8b3ac',
        name: 'View budget',
        slug: 'view-budget',
        description: 'View budget',
        permissionGroupId: permissionGroups[16].id,
      },
      {
        id: 'cbf4b3b0-0b1b-4b3b-8b3b-0b1ba3b8b3ad',
        name: 'Create deliveries',
        slug: 'create-deliveries',
        description: 'Create deliveries',
        permissionGroupId: permissionGroups[18].id,
      },
      {
        id: 'cbf4b3b0-0b1b-4b3b-8b3b-0b1ba3b8b3ae',
        name: 'Update deliveries',
        slug: 'update-deliveries',
        description: 'Update deliveries',
        permissionGroupId: permissionGroups[18].id,
      },
      {
        id: 'cbf4b3b0-0b1b-4b3b-8b3b-0b1ba3b8b3af',
        name: 'Delete deliveries',
        slug: 'delete-deliveries',
        description: 'Delete deliveries',
        permissionGroupId: permissionGroups[18].id,
      },
      {
        id: 'cbf4b3b0-0b1b-4b3b-8b3b-0b1ba3b8b3ag',
        name: 'View deliveries',
        slug: 'view-deliveries',
        description: 'View deliveries',
        permissionGroupId: permissionGroups[18].id,
      },
      {
        id: 'cbf4b3b0-0b1b-4b3b-8b3b-0b1ba3b8b4a',
        name: 'Create sponsor',
        slug: 'create-sponsor',
        description: 'Create sponsor',
        permissionGroupId: permissionGroups[19].id,
      },
      {
        id: 'cbf4b3b0-0b1b-4b3b-8b3b-0b1ba3b8b4b',
        name: 'View sponsor',
        slug: 'view-sponsor',
        description: 'View sponsor',
        permissionGroupId: permissionGroups[19].id,
      },
      {
        id: 'cbf4b3b0-0b1b-4b3b-8b3b-0b1ba3b8b4c',
        name: 'Create eCRF',
        slug: 'create-ecrf',
        description: 'Create eCRF',
        permissionGroupId: permissionGroups[7].id,
      },
      {
        id: 'cbf4b3b0-0b1b-4b3b-8b3b-0b1ba3b8b4f',
        name: 'Update eCRF',
        slug: 'update-ecrf',
        description: 'Create eCRF',
        permissionGroupId: permissionGroups[7].id,
      },
      {
        id: 'cbf4b3b0-0b1b-4b3b-8b3b-0b1ba3b8b4d',
        name: 'View eCRF',
        slug: 'view-ecrf',
        description: 'Create eCRF',
        permissionGroupId: permissionGroups[7].id,
      },
      {
        id: 'cbf4b3b0-0b1b-4b3b-8b3b-0b1ba3b8b4e',
        name: 'Delete eCRF',
        slug: 'delete-ecrf',
        description: 'Create eCRF',
        permissionGroupId: permissionGroups[7].id,
      }
    ]); 
  }
}
